# Generated by Django 5.1.4 on 2025-02-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinuser',
            name='phone_number',
            field=models.CharField(default='008', max_length=15),
        ),
    ]
