# Generated by Django 5.1.7 on 2025-03-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_pinuser_is_number_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinuser',
            name='is_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
