# Generated by Django 5.1.4 on 2025-02-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='series',
        ),
        migrations.AddField(
            model_name='pin',
            name='series_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
