# Generated by Django 5.1.4 on 2025-02-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_remove_pin_series_pin_series_name'),
        ('pins', '0002_tradingboard'),
    ]

    operations = [
    ]
