# Generated by Django 5.1.4 on 2025-02-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_tradelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingboard',
            old_name='listed_at',
            new_name='added_at',
        ),
        migrations.RemoveField(
            model_name='tradingboard',
            name='status',
        ),
        migrations.DeleteModel(
            name='Tradelist',
        ),
    ]
