# Generated by Django 5.1.4 on 2025-02-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_rename_listed_at_tradingboard_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='original_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pin',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
