# Generated by Django 5.1.4 on 2025-01-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
