# Generated by Django 5.1.4 on 2025-01-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_pin_image_url_alter_pin_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.URLField(),
        ),
        migrations.RemoveField(
            model_name='pin',
            name='tags',
        ),
        migrations.AddField(
            model_name='pin',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
