# Generated by Django 5.1.4 on 2025-01-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_remove_pin_image_url_alter_pin_image_remove_pin_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.ImageField(upload_to='pin_images/'),
        ),
    ]
