name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/pin-collection:$GITHUB_SHA .

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/pin-collection:$GITHUB_SHA

    - name: Deploy to GCP
      run: |
        gcloud run deploy pin-collection \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/pin-collection:$GITHUB_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
